- chrome/locale/fr/options.dtd
> Update french translation

- chrome/locale/fr/options.dtd
Update terms "display.favicon.show.label", "display.keySecure.label", "arh.replaceAddonResult.label") on options.dtd
> Update French translation #74

- chrome/locale/fr/options.dtd
> French localization update for 2.0.0

- chrome/locale/hu/dkim.properties
- chrome/locale/hu/options.dtd
Please advise when this has been merged so we can delete our fork. Thank you
> hu localization

- chrome/locale/it/dkim.properties
- chrome/locale/it/options.dtd
> Update Italian translation

- _locales/hu/messages.json
https://github.com/lieser/dkim_verifier/issues/224
> Update hu translation

- _locales/fr/messages.json
> feat(lang): Update french translation

- modules/ARHParser.jsm
This pull request contains two commits.
- The first one is just a refactor of ARHParser.jsm (for better comparability with the 4.0.0 version)
- The second one contains the fixes for https://github.com/lieser/dkim_verifier/commit/e1134200365eeffa20b14e10a0c173324b719e3f and https://github.com/lieser/dkim_verifier/commit/c32c8aef0984121a043b5cf4108afc69734d6165
> Fix version and id parsing

- _locales/pt_BR/description.txt
- _locales/pt_BR/developerComments.txt
- _locales/pt_BR/messages.json
- _locales/pt_BR/privacyPolicy.txt
I wanted to help locate this extension in my country.
> Add Brazilian Portuguese translation

- _locales/it/messages.json
> Update Italian translations

- _locales/it/messages.json
See https://github.com/lieser/dkim_verifier/issues/286#issuecomment-1019485837
> Revert message descriptions to en_US in Italian translations

- _locales/en_US/messages.json
- _locales/it/messages.json
> Add new Italian translations

- data/signersDefault.json
Automatic forum notifications are sent from support@tracker-software.com, but are unsigned, so adding an exception for this address...
> Update sign rules 2.x 2023-01-25

- _locales/pt_BR/messages.json
Basic proofreading, correcting only the most noticeable errors, i.e., perhaps more errors can be found in a thorough proofreading.
> Update Brazilian Portuguese translations

- chrome/locale/de/dkim.properties
- chrome/locale/en-US/dkim.properties
Understood the error message wrong, so tried to improve the message (and added a dash)
> Translate de 2.x improvements 2023-01-25

- modules/MsgReader.jsm
Backported the changes to message parsing
> Backport fix 5->2.x: accept empty body in mails

- _locales/uk/messages.json
> Update UK messages.json

- _locales/zh_TW/messages.json
> Update zh_TW translation.

- _locales/uk/messages.json
> Update UK translation

- manifest.json
- modules/dkim/signRules.mjs.js
- test/unittest/signRulesSpec.mjs.js
Allow multiple '*' globs in the From pattern.
> Multiglob_support

- modules/rfcParser.jsm.js
> 2.x: Backport: Allow up to 3 levels of nested comments in ARH

- _locales/pt_BR/messages.json
> Update Brazilian Portuguese translation

- _locales/pl/messages.json
added a few lines in the details.  section
> Update messages.json with pl translation

- _locales/fr/messages.json
> #480 - Update FR translation for v5.5.0

- _locales/ja_JP/messages.json
https://github.com/lieser/dkim_verifier/issues/480
> Update ja_JP translation for v5.5.0 (#480)

- modules/DNSWrapper.jsm.js
- modules/dkimDMARC.jsm.js
- modules/dkimKey.jsm.js
Hi,
in two commits:
- Cleaning white space (as this is now done automatically on saving...)
- Backported the central check of DNS results
> Backport 5x to 2x: Centralized DNS check 2025-01-20

- _locales/vi_VN/messages.json
Added translation for `options_showDKIM.value.33` and `button.options`
> Translate two strings to vi_VN

- _locales/zh_TW/messages.json
> Update zh_TW for 6.1.0

- _locales/vi_VN/messages.json
Add options_color.preview translation
> Update vi_VN messages for #535

- _locales/zh_TW/messages.json
> Update zh_tw translation for 6.2.0
